// AUTO-GENERATED by tools/mod-tool — do not hand-edit this file directly. Adding or removing a
// minigame here means running the mod tool (npm run mod-tool), which regenerates this barrel and
// the matching entry in src/config/game.config.json for you. See tools/mod-tool/README.md.
import stroop from './Stroop.js';
import swipe from './Swipe.js';
import whackAMole from './WhackAMole.js';

export const REGISTRY = [stroop, swipe, whackAMole];
