// Standalone game-config editor. Plain Node http/fs — no framework, no extra dependencies.
// Run with `npm run mod-tool` from the project root. Serves its own admin UI on a separate port
// from the game's own dev server (npm run dev), and only ever talks to itself over 127.0.0.1.
import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PORT = 5175;
const HOST = '127.0.0.1'; // never bind wider than loopback — this server can write files

const PROJECT_ROOT = path.resolve(__dirname, '..', '..');
const CONFIG_PATH = path.join(PROJECT_ROOT, 'src', 'config', 'game.config.json');
const REGISTRY_DIR = path.join(PROJECT_ROOT, 'src', 'render', 'puzzles', 'registry');
const REGISTRY_INDEX = path.join(REGISTRY_DIR, 'index.js');
const SOUNDS_DIR = path.join(PROJECT_ROOT, 'public', 'Sounds');
const AVATARS_DIR = path.join(PROJECT_ROOT, 'public', 'UI', 'Avatars');
const TEMPLATE_PATH = path.join(__dirname, 'templates', 'minigame.template.js');
const PUBLIC_DIR = path.join(__dirname, 'public');

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
};

// --- filesystem helpers ---

// Reduces any client-supplied name to its basename and rejects traversal attempts before it's
// ever joined into a real path — this server has file-write endpoints, so this is load-bearing,
// not decorative.
function safeFilename(name) {
  const base = path.basename(String(name || ''));
  if (!base || base === '.' || base === '..' || base.includes('/') || base.includes('\\')) {
    throw new Error(`Invalid filename: ${name}`);
  }
  return base;
}

function readConfig() {
  return JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8'));
}

// Write-temp-then-rename so a crash or overlapping request never leaves game.config.json
// half-written. Handlers use synchronous fs calls throughout, which is enough to serialize
// concurrent requests safely on Node's single-threaded event loop for a single-user local tool.
function writeConfig(config) {
  const tmp = `${CONFIG_PATH}.tmp-${process.pid}`;
  fs.writeFileSync(tmp, JSON.stringify(config, null, 2));
  fs.renameSync(tmp, CONFIG_PATH);
}

function scanDir(dir, extFilter) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter((f) => (extFilter ? extFilter.test(f) : true));
}

function pascalCase(id) {
  return id.charAt(0).toUpperCase() + id.slice(1);
}

// Regenerates the registry barrel from whatever .js files actually exist in REGISTRY_DIR (not
// from the config list) — self-healing if a file is ever added/removed by hand.
function regenerateRegistryIndex() {
  const files = scanDir(REGISTRY_DIR, /\.js$/).filter((f) => f !== 'index.js');
  const entries = files.map((f) => ({
    varName: path.basename(f, '.js').replace(/^./, (c) => c.toLowerCase()),
    file: f,
  }));
  const importLines = entries.map((e) => `import ${e.varName} from './${e.file}';`).join('\n');
  const exportLine = `export const REGISTRY = [${entries.map((e) => e.varName).join(', ')}];`;
  const content =
    `// AUTO-GENERATED by tools/mod-tool — do not hand-edit this file directly. Adding or removing a\n` +
    `// minigame here means running the mod tool (npm run mod-tool), which regenerates this barrel and\n` +
    `// the matching entry in src/config/game.config.json for you. See tools/mod-tool/README.md.\n` +
    `${importLines}\n\n${exportLine}\n`;
  fs.writeFileSync(REGISTRY_INDEX, content);
}

function scaffoldMinigame(id, title) {
  if (!/^[a-z][a-zA-Z0-9]*$/.test(id)) {
    throw new Error('id must start with a lowercase letter and contain only letters/numbers');
  }
  const filePath = path.join(REGISTRY_DIR, `${pascalCase(id)}.js`);
  if (fs.existsSync(filePath)) throw new Error(`A minigame file already exists for id "${id}"`);

  const template = fs
    .readFileSync(TEMPLATE_PATH, 'utf8')
    .replace(/__ID__/g, id)
    .replace(/__TITLE__/g, (title || id).toUpperCase());
  fs.writeFileSync(filePath, template);
  regenerateRegistryIndex();

  const config = readConfig();
  config.minigames.push({ id, enabled: true });
  writeConfig(config);
}

function removeMinigame(id, deleteFile) {
  const config = readConfig();
  const entry = config.minigames.find((m) => m.id === id);
  if (!entry) throw new Error(`Unknown minigame id "${id}"`);

  if (deleteFile) {
    const filePath = path.join(REGISTRY_DIR, `${pascalCase(id)}.js`);
    if (fs.existsSync(filePath)) fs.unlinkSync(filePath);
    config.minigames = config.minigames.filter((m) => m.id !== id);
    regenerateRegistryIndex();
  } else {
    entry.enabled = false;
  }
  writeConfig(config);
}

// --- request body / response helpers ---

function readJsonBody(req) {
  return new Promise((resolve, reject) => {
    let data = '';
    req.on('data', (chunk) => (data += chunk));
    req.on('end', () => {
      try {
        resolve(data ? JSON.parse(data) : {});
      } catch (err) {
        reject(err);
      }
    });
    req.on('error', reject);
  });
}

function sendJson(res, status, body) {
  const payload = JSON.stringify(body);
  res.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8' });
  res.end(payload);
}

const GAME_PUBLIC_DIR = path.join(PROJECT_ROOT, 'public');

// Serves the tool's own admin UI first; anything not found there falls back to the game's own
// public/ folder (unmodified — read-only from this route) so the config's asset paths
// (/UI/Avatars/..., /Sounds/...) resolve as-is for thumbnail/preview purposes in the tool UI,
// without needing any path rewriting in app.js.
function serveStatic(req, res, pathname) {
  const rel = pathname === '/' ? '/index.html' : pathname;
  const toolPath = path.join(PUBLIC_DIR, rel);
  const gamePath = path.join(GAME_PUBLIC_DIR, rel);
  if (!toolPath.startsWith(PUBLIC_DIR) || !gamePath.startsWith(GAME_PUBLIC_DIR)) {
    res.writeHead(403);
    res.end('Forbidden');
    return;
  }

  fs.readFile(toolPath, (toolErr, toolData) => {
    if (!toolErr) {
      res.writeHead(200, { 'Content-Type': MIME[path.extname(toolPath)] || 'application/octet-stream' });
      res.end(toolData);
      return;
    }
    fs.readFile(gamePath, (gameErr, gameData) => {
      if (gameErr) {
        res.writeHead(404);
        res.end('Not found');
        return;
      }
      res.writeHead(200, { 'Content-Type': MIME[path.extname(gamePath)] || 'application/octet-stream' });
      res.end(gameData);
    });
  });
}

// --- routes ---

const server = http.createServer(async (req, res) => {
  const url = new URL(req.url, `http://${req.headers.host}`);
  const { pathname } = url;

  try {
    if (req.method === 'GET' && pathname === '/api/config') {
      const config = readConfig();
      sendJson(res, 200, {
        config,
        discovered: {
          minigameFiles: scanDir(REGISTRY_DIR, /\.js$/).filter((f) => f !== 'index.js'),
          soundFiles: scanDir(SOUNDS_DIR, null),
          avatarFiles: scanDir(AVATARS_DIR, /\.png$/),
        },
      });
      return;
    }

    if (req.method === 'POST' && pathname === '/api/config') {
      const body = await readJsonBody(req);
      if (!body.settings || !body.minigames || !body.sounds || !body.avatarParts) {
        sendJson(res, 400, { error: 'Config is missing one of settings/minigames/sounds/avatarParts' });
        return;
      }
      writeConfig(body);
      sendJson(res, 200, { ok: true });
      return;
    }

    if (req.method === 'POST' && pathname === '/api/minigame/scaffold') {
      const { id, title } = await readJsonBody(req);
      scaffoldMinigame(id, title);
      sendJson(res, 200, { ok: true });
      return;
    }

    if (req.method === 'POST' && pathname === '/api/minigame/remove') {
      const { id, deleteFile } = await readJsonBody(req);
      removeMinigame(id, !!deleteFile);
      sendJson(res, 200, { ok: true });
      return;
    }

    if (req.method === 'POST' && pathname === '/api/sound/upload') {
      const { key, filename, dataBase64 } = await readJsonBody(req);
      const safeName = safeFilename(filename);
      fs.writeFileSync(path.join(SOUNDS_DIR, safeName), Buffer.from(dataBase64, 'base64'));

      const config = readConfig();
      const urlPath = `/Sounds/${safeName}`;
      if (!config.sounds[key]) config.sounds[key] = { files: [] };
      if (!config.sounds[key].files.includes(urlPath)) config.sounds[key].files.push(urlPath);
      writeConfig(config);
      sendJson(res, 200, { ok: true, urlPath });
      return;
    }

    if (req.method === 'POST' && pathname === '/api/avatar/upload') {
      const { category, filename, dataBase64 } = await readJsonBody(req);
      const safeName = safeFilename(filename);
      fs.writeFileSync(path.join(AVATARS_DIR, safeName), Buffer.from(dataBase64, 'base64'));

      const config = readConfig();
      const urlPath = `/UI/Avatars/${safeName}`;
      const cat = config.avatarParts.categories.find((c) => c.key === category);
      if (!cat) throw new Error(`Unknown avatar category "${category}"`);
      if (!cat.options.includes(urlPath)) cat.options.push(urlPath);
      writeConfig(config);
      sendJson(res, 200, { ok: true, urlPath });
      return;
    }

    if (req.method === 'POST' && pathname === '/api/avatar/category') {
      const { key, label } = await readJsonBody(req);
      if (!/^[a-z][a-zA-Z0-9]*$/.test(key)) throw new Error('category key must be lowercase letters/numbers');
      const config = readConfig();
      if (config.avatarParts.categories.some((c) => c.key === key)) {
        throw new Error(`Category "${key}" already exists`);
      }
      config.avatarParts.categories.push({ key, label: label || key, options: [] });
      writeConfig(config);
      sendJson(res, 200, { ok: true });
      return;
    }

    if (req.method === 'GET') {
      serveStatic(req, res, pathname);
      return;
    }

    sendJson(res, 404, { error: 'Not found' });
  } catch (err) {
    sendJson(res, 400, { error: err.message });
  }
});

server.listen(PORT, HOST, () => {
  console.log(`Mod tool running at http://${HOST}:${PORT} (project: ${PROJECT_ROOT})`);
});
